title: Notetask
description: |
  What is it?
  Do you often save important ideas, to-do lists, phone numbers, or command-line snippets in random text files, hoping to find them later… only to forget where exactly you put them? No more wasted time searching — Notetask helps bring order to the chaos!

  All your notes can be stored locally on your device — no clouds, no third parties.

  This handy desktop app helps you organize your tasks, capture ideas, and manage your lists — with no more confusion!

  Notetask is a cross-platform application for managing task lists that include completion status, task description, and notes. Each task can have a due date and be marked as a favorite with a star. It uses its own storage text format based on Markdown.